In [1]:
import numpy as np


print(np.random.random(), np.random.rand())

0.3896160849294491 0.8428338697206172


In [2]:
n = 5
A = np.array([np.ones(n) for i in range(n)])

print(np.sum(A))

25.0


In [3]:
print(np.ones((30, 30)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.delete(a, np.arange(3,6))

print(a)

[1 2 3 7 8 9]


In [5]:
b = np.array([])
b = np.append(b, [a, a])
print(b)

[1. 2. 3. 7. 8. 9. 1. 2. 3. 7. 8. 9.]


In [7]:
b = b.tolist()
print(b)
b = np.delete(b, np.arange(3,6))
print(b)
b = np.append(b, [a, a])
print(b)

[1.0, 2.0, 3.0, 1.0, 2.0, 3.0, 7.0, 8.0, 9.0]
[1. 2. 3. 7. 8. 9.]
[1. 2. 3. 7. 8. 9. 1. 2. 3. 7. 8. 9. 1. 2. 3. 7. 8. 9.]


In [9]:
print(type(np.random.randint(1, 3, 1)[0]))

<class 'numpy.int64'>


In [12]:
u = np.linspace(0, 100, 400, endpoint=True)
print(100/399, u[1]-u[0])

0.2506265664160401 0.2506265664160401


In [13]:
for i in range(100):
    print(1 - 2 * np.random.rand())

0.9371177403827382
0.8609100841455313
-0.2610181646692393
0.0662162595348812
0.05370157376540363
-0.25806263384189254
0.4680564058124601
-0.6908335101925953
0.6282171122664422
0.6566636712733791
0.3924075334491244
0.2813020036471434
-0.492553909384126
0.9762184875436706
-0.9325504760721108
-0.22055756281165428
0.6294222330046859
0.33836295046139675
0.058495909325455564
0.7030476362368929
-0.9032062495124051
-0.332385971564797
0.9590402514985514
0.41221157286853116
0.7782129894722458
-0.4016852217266036
0.2102816435885535
-0.3785996949298107
-0.18848155705885028
-0.9493919227704357
-0.7352929534116819
-0.31788953443241663
-0.7448829069766589
-0.40996621996630966
0.3194993767221421
0.7149220276166652
-0.29001238310417365
0.8480202062356872
0.43879661318185037
0.8825971717077394
0.9777903884349939
0.6063530522621041
-0.14649382604660754
-0.8989227706794831
-0.18790977646032014
-0.5227576954861854
0.6789237509804975
0.9413714484352531
0.968643502243028
0.7204584920938226
-0.000374626069047