In [1]:
import numpy as np


print(np.random.random(), np.random.rand())

0.3896160849294491 0.8428338697206172


In [2]:
n = 5
A = np.array([np.ones(n) for i in range(n)])

print(np.sum(A))

25.0


In [3]:
print(np.ones((30, 30)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.delete(a, np.arange(3,6))

print(a)

[1 2 3 7 8 9]


In [5]:
b = np.array([])
b = np.append(b, [a, a])
print(b)

[1. 2. 3. 7. 8. 9. 1. 2. 3. 7. 8. 9.]


In [7]:
b = b.tolist()
print(b)
b = np.delete(b, np.arange(3,6))
print(b)
b = np.append(b, [a, a])
print(b)

[1.0, 2.0, 3.0, 1.0, 2.0, 3.0, 7.0, 8.0, 9.0]
[1. 2. 3. 7. 8. 9.]
[1. 2. 3. 7. 8. 9. 1. 2. 3. 7. 8. 9. 1. 2. 3. 7. 8. 9.]


In [9]:
print(type(np.random.randint(1, 3, 1)[0]))

<class 'numpy.int64'>
